### ISSUE TITLE
API 연계

### ISSUE THREAD

**Issue by ltlapy** [bufs-newclear/PDI-App#3]
## TODO
- [ ] API 설계
  - [ ] 데이터 형식 설계
- [ ] API 가져오기
- [ ] 예외 처리
  - [ ] 이미지를 가져오지 못했을 경우
  - [ ] 식단 API 오류

**Comment by ltlapy** [comment]
백엔드 소프트웨어 개발을 시작한 다음에 구현하는 게 좋을까...?
